package com.example.ballinonabudget;
/**
 * @author: Caroline Rankin (crrankin)
 * This class represents a monthly budget
 * that allows a user to create a name, amount, and items.
 * Each budget has a unique identifier.
 */

import java.util.HashMap;
import androidx.room.Entity;

@Entity(tableName = "Budget")
public class Budget {

    @PrimaryKey(autoGenerate = true)
    private int id; //id is autogenerated in case that a user makes budgets with the same name

    private String name; //name of the budget. Eg: "May Budget"
    private double totalAmount; //total amount for the entire budget
    private HashMap<String, Double> items; //list of the purchases/items in the budget

    /**
     * Constructs a budget
     * @param name
     * @param totalAmount
     * @param purchases
     */
    public Budget(String name, double totalAmount, HashMap<String, Double> purchases){
        this.name = name;
        this.totalAmount = totalAmount;
        this.items = purchases;
    }

    //Getters and Setters for private variables
    public int getID(){ return id; }
    public String getName(){ return name; }
    public void setName(String name){ this.name = name; }
    public double getTotalAmount(){ return totalAmount; }
    public void setTotalAmount(double totalAmount){ this.totalAmount = totalAmount; }

}
